### PR TITLE
install yarn dependencies for retract

### PR DESCRIPTION
**Pull request by asottile-sentry**
followup to #1359

### CODE REVIEW

**Review by AbhiPrasad — APPROVED** [review]

**Comment by BYK** [comment]
Looking back on this, I think using a combination of Yarn v3 and its zero-install system, you can eliminate the `yarn install` step from action runs. What do you think?

**Comment by asottile-sentry** [comment]
checking in all the dependencies rubs me the wrong way at the very least

**Comment by asottile-sentry** [comment]
ah I thought you meant this part of zero-install: https://yarnpkg.com/features/offline-cache

**Comment by asottile-sentry** [comment]
ok so I wasn't wrong above :P

**Comment by BYK** [comment]
It's quite different from checking in `node_modules` that's why I pushed back a bit 😅

**Comment by asottile-sentry** [comment]
it still balloons the repository size and introduces lots of large blobs which git does not handle well and stay with the repository indefinitely -- but yeah I'm not interested in arguing about that lol

**Pull request merged**
