### PR TITLE
feat: Auto-approve releases of sentry-redis-tools

### PR DESCRIPTION
**Pull request by untitaker**
https://github.com/getsentry/sentry-redis-tools

### CODE REVIEW

**Comment by BYK** [comment]
It feels like it might be a good time to extract this list to its own file now?

**Comment by untitaker** [comment]
probably though the file as a whole isn't particularly large yet. also I believe it would require me to execute that logic in bash instead of `if:`, right?

**Comment by asottile-sentry** [comment]
it's already in its own file -- extraction just adds indirection for no benefit

**Review by asottile-sentry — APPROVED** [review]

**Comment by BYK** [comment]
@untitaker not necessarily bash. It adds a bit of an overhad but you can have a previous step that reads the file and emits that as it's output and then [use `contains`](https://docs.github.com/en/actions/learn-github-actions/expressions#example-using-an-object-filter) to do something like this:

```yaml
name: auto-approve non-sdks
on:
  issues:
    types: [opened]
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: repo
        run: echo '${{ github.event.issue.title }}' | sed -nr 's#^publish: getsentry/([[:alnum:]]+)@#::set-output name=name::\1#p'
      - id: allow-list
        run:  |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "AUTO_APPROVE_REPOS<<$EOF" >> $GITHUB_ENV
          cat <file> >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV
      - if: |
	      github.actor == 'getsentry-release' &&
          contains(fromJSON(env.AUTO_APPROVE_REPOS), steps.repo.outputs.name)
        run: gh issue edit ${{ github.event.issue.html_url }} --add-label accepted
        env:
          # can't use `GITHUB_TOKEN` because we need to trigger actions
          GH_TOKEN: ${{ secrets.GH_SENTRY_BOT_PAT }}
```

**Comment by BYK** [comment]
>it's already in its own file -- extraction just adds indirection for no benefit

It does as it separates data from the code so when you are just adding a new repo, you have 0 chance of breaking the code by forgetting some part of the boilerplate.

Given my example above, the usefulness or importance of that concern is questionable given the added complexity tho.

**Comment by untitaker** [comment]
Makes sense. I don't think this is something we want right now unless there is e.g. a need to read this data from another piece of code (for some auditability reason). But right now I feel -0 on it

**Comment by BYK** [comment]
Re, the example code above: it can probably reuse the following part from `publish.yaml`:

https://github.com/getsentry/publish/blob/02b4a776ffa38acd09b1e54cfa398679dbea3f4b/.github/workflows/publish.yml#L29-L31

**Comment by asottile-sentry** [comment]
I'm a full -1 -- when it's in a separate file, extra code to read and manage that file, and overhead to read and understand the file.

plus it then needs to _execute_ whereas right now the job is skipped entirely

**Comment by asottile-sentry** [comment]
abstracting _from what_? there are no benefits.  also why do you care?

**Comment by BYK** [comment]
>also why do you care?

Because I'm the author of this entire system and it also happens to be open source. Is this how you treat your community?

**Pull request merged**
