### PR TITLE
Add sequence diagram to README

### PR DESCRIPTION
**Pull request by chadwhitacre**

### CODE REVIEW

**Review by BYK — APPROVED** [review]
This looks great, thank you!

Can you make the link point to the source code for this diagram instead of the image itself tho?

**Comment by chadwhitacre** [comment]
I had that in the first commit, it seemed too confusing for the casual reader but I can bring it back if you want.

**Comment by chadwhitacre** [comment]
How about linking to presentation mode, @BYK?

**Review by BYK — APPROVED** [review]

**Comment by chadwhitacre** [comment]
I do have the source code stored in a Google Doc but it seems fine to also store it base64-encoded in the README. :)

**Pull request merged**
