### PR TITLE
refactor(calver): Remove disabled calver workflow [DEVINFRA-89]

### PR DESCRIPTION
**Pull request by mattgauntseo-sentry**
This workflow was disabled 7 months ago so it should be safe to remove.

### CODE REVIEW

**Review by chadwhitacre — APPROVED** [review]
RIP

**Review by asottile-sentry — APPROVED** [review]

**Comment by BYK** [comment]
@chadwhitacre all manual releases since then? 😮

**Comment by chadwhitacre** [comment]
Yes, the self-hosted process still breaks so often that we have to plan to babysit it, in which case applying a few "accept" labels is not so much trouble. Maybe some day we can bring this back! :)

**Pull request merged**
